language: go
go:
  - 1.14.x
  - 1.15.x

before_install:
    - go get -t -v ./...

install:
    - go get github.com/cupen/signalhandler

script:
    - go test -coverprofile=coverage.txt -v -bench .

after_success:
    - bash <(curl -s https://codecov.io/bash)